nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/tomleb/rancher-extensions/gh-pages/extensions/sqlite-explorer/2.0.0
  compressedEndpoint: >-
    https://raw.githubusercontent.com/tomleb/rancher-extensions/gh-pages/extensions/sqlite-explorer/2.0.0.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.10.0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
